#!/usr/bin/env bash

set -e

echo "======================================"
echo " Superserve Chrome Remote Desktop Setup"
echo "======================================"

# Check architecture
ARCH=$(dpkg --print-architecture)

if [ "$ARCH" != "amd64" ]; then
    echo "ERROR: Chrome Remote Desktop Debian package requires amd64."
    echo "Current architecture: $ARCH"
    exit 1
fi

# Check root
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: Please run this script as root."
    exit 1
fi

export DEBIAN_FRONTEND=noninteractive

echo "[1/7] Updating system..."
apt update
apt --fix-broken install -y
dpkg --configure -a || true

echo "[2/7] Installing required packages..."
apt install -y \
    curl \
    wget \
    sudo \
    gnupg \
    ca-certificates \
    dbus-x11 \
    xfce4 \
    desktop-base \
    xfce4-terminal \
    xscreensaver

echo "[3/7] Installing Chrome Remote Desktop..."

# Google signing key
curl -fsSL https://dl.google.com/linux/linux_signing_key.pub \
    | gpg --dearmor \
    -o /etc/apt/trusted.gpg.d/chrome-remote-desktop.gpg

echo "deb [arch=amd64] https://dl.google.com/linux/chrome-remote-desktop/deb stable main" \
    > /etc/apt/sources.list.d/chrome-remote-desktop.list

apt update

apt install -y chrome-remote-desktop

echo "[4/7] Configuring XFCE..."

cat > /etc/chrome-remote-desktop-session << 'EOF'
exec /etc/X11/Xsession /usr/bin/xfce4-session
EOF

chmod +x /etc/chrome-remote-desktop-session

echo "[5/7] Creating CRD user..."

CRD_USER="crd"

if ! id "$CRD_USER" >/dev/null 2>&1; then
    useradd -m -s /bin/bash "$CRD_USER"
fi

echo "$CRD_USER ALL=(ALL) NOPASSWD:ALL" \
    > /etc/sudoers.d/crd

chmod 440 /etc/sudoers.d/crd

if getent group chrome-remote-desktop >/dev/null 2>&1; then
    usermod -aG chrome-remote-desktop "$CRD_USER"
fi

echo "[6/7] Checking CRD installation..."

if [ ! -f /opt/google/chrome-remote-desktop/start-host ]; then
    echo ""
    echo "ERROR!"
    echo "Chrome Remote Desktop start-host was not installed."
    echo ""
    dpkg -l | grep chrome || true
    exit 1
fi

echo ""
echo "======================================"
echo " INSTALLATION COMPLETE"
echo "======================================"
echo ""
echo "Now open this on your phone/PC:"
echo "https://remotedesktop.google.com/headless"
echo ""
echo "1. Login with your Google account"
echo "2. Choose Set up another computer"
echo "3. Authorize"
echo "4. Copy the COMPLETE Linux command"
echo ""
echo "Then paste it below."
echo ""
echo "IMPORTANT:"
echo "Do NOT paste your Google password."
echo "Only paste the command generated by Google."
echo ""

read -r -p "Paste CRD command: " CRD_COMMAND

echo ""
echo "[7/7] Starting Chrome Remote Desktop..."

# Run Google's generated CRD command as the CRD user.
su - "$CRD_USER" -c "$CRD_COMMAND"

echo ""
echo "======================================"
echo " CRD SETUP COMMAND FINISHED"
echo "======================================"
echo ""
echo "Check Remote Desktop here:"
echo "https://remotedesktop.google.com/access"
echo ""
echo "Sandbox hostname:"
hostname
echo ""
echo "NOTE:"
echo "Superserve does not use systemd in your current environment,"
echo "so 'systemctl status chrome-remote-desktop' may fail."
echo ""
